language: node_js

node_js:
  - 8

notifications:
  email:
    recipients:
      - ilanguagelab-dev@googlegroups.com
    on_success: change
    on_failure: always

before_install:
  # Download and configure deps
  - npm install -g gulp
  - npm install -g jasmine-node
  # npm install -g git://github.com/kacperus/jasmine-node.git &&
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - npm install canvas-browserify

# before_script:
  # Make sure the emulator has started before running tests

script: gulp
